---
title: "STA 222 Final Project"
output: html_document
date: "2022-12-03"
---

#### Loading Libraries

```{r}
library(survival)
library(KMsurv)
library(ggplot2)
library(ggpubr)
library(survminer)
library(muhaz)
library(plyr)
library(plotly)
library(ggthemes)
library(MASS)
```

#### Cleaning Data
 
```{r}
# Loading in data
data(std)
# Checking for NA Values in data set 
any(is.na(std))

factor.cols <-
  c(
    "race",
    # Race (W=white, B=black)
    "marital",
    # Marital status (D=divorced / separated, M=married, S=single)
    "iinfct",
    # Initial infection (1= gonorrhea, 2=chlamydia, 3=both)
    "os12m",
    # Oral sex within 12 months (1=yes, 0=no)
    "os30d",
    # Oral sex within 30 days (1=yes, 0=no)
    "rs12m",
    # Rectal sex within 12 months (1=yes, 0=no)
    "rs30d",
    # Rectal sex within 30 days (1=yes, 0=no)
    "abdpain",
    # Presence of abdominal pain (1=yes, 0=no)
    "discharge",
    # Sign of discharge (1=yes, 0=no)
    "dysuria",
    # Sign of dysuria (1=yes, 0=no)
    "condom",
    # Condom use (1=always, 2=sometime, 3=never)
    "itch",
    # Sign of itch (1=yes, 0=no)
    "lesion",
    # Sign of lesion (1=yes, 0=no)
    "rash",
    # Sign of rash (1=yes, 0=no)
    "lymph",
    # Sign of lymph (1=yes, 0=no)
    "vagina",
    # Involvement vagina at exam (1=yes, 0=no)
    "dchexam",
    # Discharge at exam (1=yes, 0=no)
    "abnode" # Abnormal node at exam (1=yes, 0=no)
  )
std[factor.cols] <- lapply(std[factor.cols], as.factor)
#lapply(std, class)
std$race <-
  mapvalues(std$race,
            from = c("W", "B"),
            to = c("White", "Black"))
std$marital <-
  mapvalues(
    std$marital,
    from = c("D", "M", "S"),
    to = c("Divorced/Separated", "Married", "Single")
  )
std$iinfct <-
  mapvalues(
    std$iinfct,
    from = c("1", "2", "3"),
    to = c("gonorrhea", "chlamydia", "both")
  )
std$condom <-
  mapvalues(
    std$condom,
    from = c("1", "2", "3"),
    to = c("always", "sometime", "never")
  )
```

#### Exploratory Data Analysis

```{r}

```

#### Checking Model Assumptions

```{r}
# Building the Survival Object 
infect <- std$iinfct
surv_object <- Surv(time = std$time, event = std$rinfct)
```

#### Building the Model

```{r}

```

#### Checking the Model

```{r}

```

#### Outliers

```{r}

```