---
title: "Initial Set Up"
author: "Gianni Spiga"
date: '2022-11-22'
output: 
  ioslides_presentation:
    widescreen: TRUE

---

# In the morning

```{r, message = FALSE, warning=FALSE}
library(survival)
library(KMsurv)
library(ggplot2)
library(ggpubr)
library(survminer)
library(plotly)
library(muhaz)
library(ggthemes)
```

## Getting up

```{r, fig.cap="Sample", echo = F}
#data(pneumon)
#ggplotly(ggplot(data = pneumon, aes(x = smoke)) + geom_histogram(stat = "count"))
```

# Loading in Data

```{r, echo=F}
# Loading in data
data(std)

# Checking for NA Values in dataset 
any(is.na(std))

# 
# #Check data type for each column
# sapply(pneumon, class)
# 
# # #We turn columns desired into factors
# # factor.cols <-
# #   c(
# #     "hospital",
# #     "urban",
# #     "alcohol",
# #     "smoke",
# #     "region",
# #     "poverty",
# #     "bweight",
# #     "race",
# #     "wmonth",
# #     "sfmonth"
# #   )
# # This will turn into factors 
# #pneumon[factor.cols] <- lapply(pneumon[factor.cols], as.factor)
# 
# #Check data conversion
# str(pneumon)
# 

factor.cols <-
  c(
    "race",
    # Race (W=white, B=black)
    "marital",
    # Marital status (D=divorced / separated, M=married, S=single)
    "iinfct",
    # Initial infection (1= gonorrhea, 2=chlamydia, 3=both)
    "os12m",
    # Oral sex within 12 months (1=yes, 0=no)
    "os30d",
    # Oral sex within 30 days (1=yes, 0=no)
    "rs12m",
    # Rectal sex within 12 months (1=yes, 0=no)
    "rs30d",
    # Rectal sex within 30 days (1=yes, 0=no)
    "abdpain",
    # Presence of abdominal pain (1=yes, 0=no)
    "discharge",
    # Sign of discharge (1=yes, 0=no)
    "dysuria",
    # Sign of dysuria (1=yes, 0=no)
    "condom",
    # Condom use (1=always, 2=sometime, 3=never)
    "itch",
    # Sign of itch (1=yes, 0=no)
    "lesion",
    # Sign of lesion (1=yes, 0=no)
    "rash",
    # Sign of rash (1=yes, 0=no)
    "lymph",
    # Sign of lymph (1=yes, 0=no)
    "vagina",
    # Involvement vagina at exam (1=yes, 0=no)
    "dchexam",
    # Discharge at exam (1=yes, 0=no)
    "abnode" # Abnormal node at exam (1=yes, 0=no)
  )

std[factor.cols] <- lapply(std[factor.cols], as.factor)

#lapply(std, class)


std$race <-
  mapvalues(std$race,
            from = c("W", "B"),
            to = c("White", "Black"))
std$marital <-
  mapvalues(
    std$marital,
    from = c("D", "M", "S"),
    to = c("Divorced/Separated", "Married", "Single")
  )
std$iinfct <-
  mapvalues(
    std$iinfct,
    from = c("1", "2", "3"),
    to = c("gonorrhea", "chlamydia", "both")
  )
std$condom <-
  mapvalues(
    std$condom,
    from = c("1", "2", "3"),
    to = c("always", "sometime", "never")
  )


# Building the Survival Object 
infect <- std$iinfct
surv_object <- Surv(time = std$time, event = std$rinfct)
```

### EDA
```{r}
fig1 <-
  plot_ly(
    data = data.frame(table(std$iinfct)),
    labels = ~ Var1,
    values = ~ Freq,
    type = 'pie'
  )
fig1 <-
  fig1 %>% layout(
    title = "Percentage of Infection Type/",
    xaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    ),
    yaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    )
  )
fig1


fig2 <-
  plot_ly(
    data = data.frame(table(std$npartner)),
    labels = ~ Var1,
    values = ~ Freq,
    type = 'pie'
  )
fig2 <-
  fig2 %>% layout(
    title = "Number of Partners",
    xaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    ),
    yaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    )
  )
fig2
```


### 

### Kaplan-Meier Curves 

```{r}
KMobj <- survfit(surv_object ~ iinfct, data = std)
KMplot <- ggsurvplot(KMobj) + labs(title = "Kaplan-Meier Curves for Initial Infection Type") 
ggplotly(KMplot[[1]])
```