---
title: "Analysis on Reinfection of Sexually Transmitted Diseases"
author: "Yichu Chen, Gu Gong, Kate Jones, Gianni Spiga"
date: '2022-11-29'
output:
  slidy_presentation: 
    highlight: "espresso"
    df_print: paged
  ioslides_presentation:
    widescreen: yes
---

# Libraries Used

- Our analysis for this presenation would not have been possible without these libaries: 

```{r, message = FALSE, warning=FALSE}
library(survival)
library(KMsurv)
library(ggplot2)
library(ggpubr)
library(survminer)
library(plotly)
library(muhaz)
library(ggthemes)
library(plyr)
```

 Loading in Data
```{r}
data(std)
std
```

```{r, echo=F}
# Loading in data
#data(std)

# Checking for NA Values in data set 
any(is.na(std))

factor.cols <-
  c(
    "race",
    # Race (W=white, B=black)
    "marital",
    # Marital status (D=divorced / separated, M=married, S=single)
    "iinfct",
    # Initial infection (1= gonorrhea, 2=chlamydia, 3=both)
    "os12m",
    # Oral sex within 12 months (1=yes, 0=no)
    "os30d",
    # Oral sex within 30 days (1=yes, 0=no)
    "rs12m",
    # Rectal sex within 12 months (1=yes, 0=no)
    "rs30d",
    # Rectal sex within 30 days (1=yes, 0=no)
    "abdpain",
    # Presence of abdominal pain (1=yes, 0=no)
    "discharge",
    # Sign of discharge (1=yes, 0=no)
    "dysuria",
    # Sign of dysuria (1=yes, 0=no)
    "condom",
    # Condom use (1=always, 2=sometime, 3=never)
    "itch",
    # Sign of itch (1=yes, 0=no)
    "lesion",
    # Sign of lesion (1=yes, 0=no)
    "rash",
    # Sign of rash (1=yes, 0=no)
    "lymph",
    # Sign of lymph (1=yes, 0=no)
    "vagina",
    # Involvement vagina at exam (1=yes, 0=no)
    "dchexam",
    # Discharge at exam (1=yes, 0=no)
    "abnode" # Abnormal node at exam (1=yes, 0=no)
  )

std[factor.cols] <- lapply(std[factor.cols], as.factor)

#lapply(std, class)

std$race <-
  mapvalues(std$race,
            from = c("W", "B"),
            to = c("White", "Black"))
std$marital <-
  mapvalues(
    std$marital,
    from = c("D", "M", "S"),
    to = c("Divorced/Separated", "Married", "Single")
  )
std$iinfct <-
  mapvalues(
    std$iinfct,
    from = c("1", "2", "3"),
    to = c("gonorrhea", "chlamydia", "both")
  )
std$condom <-
  mapvalues(
    std$condom,
    from = c("1", "2", "3"),
    to = c("always", "sometime", "never")
  )
summary(std$race)
# Building the Survival Object 
infect <- std$iinfct
surv_object <- Surv(time = std$time, event = std$rinfct)
```

# Exploratory Data Analysis

Take a look at correlation between symptoms and different infection types.

Is it more common for one type of infection based on type of sex (oral/anal).

```{r, echo = F}
fig1 <-
  plot_ly(
    data = data.frame(table(std$iinfct)),
    labels = ~ Var1,
    values = ~ Freq,
    type = 'pie'
  )
fig1 <-
  fig1 %>% layout(
    title = "Percentage of Infection Type",
    xaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    ),
    yaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    )
  )
fig1

fig2 <-
  plot_ly(
    data = data.frame(table(std$npartner)),
    labels = ~ Var1,
    values = ~ Freq,
    type = 'pie'
  )
fig2 <-
  fig2 %>% layout(
    title = "Number of Partners",
    xaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    ),
    yaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    )
  )
fig2
```

# Kaplan-Meier Curves 
```{r, echo = F, warning = F}
KMobj <- survfit(surv_object ~ iinfct, data = std)
KMplot <-
  ggsurvplot(KMobj,
             palette = c("#daed64", "#6495ed", "#ed7864"),
             ggtheme = theme_fivethirtyeight()) + labs(title = "Kaplan-Meier Curves for Initial Infection Type")
ggplotly(KMplot[[1]])

survdiff(surv_object ~ iinfct, data = std)
```

# Cumulative Hazards and CLogLog

```{r, echo = F, warning = F}
# {plot(survfit(surv_object ~ iinfct, data = std),col=4:6,lwd=1,fun="cumhaz")
# title("Cumulative Hazard for intital infection")
# legend("topleft",c("gonorrhea","chlamydia","both"),col=4:6,lwd=1)}

# Interactive plot 
# Cumulative Hazard 
cumHazPlot <-
  ggsurvplot(
    KMobj,
    fun = "cumhaz",
    conf.int = FALSE,
    palette = c("#daed64", "#6495ed", "#ed7864"),
    ggtheme =theme_fivethirtyeight()
  ) + ggtitle("Cumulative Hazard for Initial Infection Type")

ggplotly(cumHazPlot$plot)


# Complimentary Log-Log 
cLogLogPlot <-
  ggsurvplot(
    KMobj,
    fun = "cloglog",
    palette = c("#daed64", "#6495ed", "#ed7864"),
    ggtheme = theme_fivethirtyeight()
  ) + ggtitle("Complimentary Log-Log for Initial Infection Type") 

ggplotly(cLogLogPlot[[1]])
```