---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(KMsurv)
library(ggplot2)
library(ggpubr)
library(survminer)
library(plotly)
library(muhaz)
library(ggthemes)
library(plyr)
library(tidyr)
```

```{r}
# Loading in data
data(std)

std0 = std
# Checking for NA Values in data set 
any(is.na(std))

# add number of symptoms column
# symptoms <- c("itch","lesion","rash","lymph", "abdpain","discharge","dysuria")
# num_symptoms = rowSums(std[,symptoms])
# num_symptoms <-
#   mapvalues(
#     num_symptoms,
#     from = c(0,1,2,3,4,5),
#     to = c("0","1","2",">2",">2",">2")
#   )
# std["num_symptoms"] = num_symptoms
# std$num_symptoms = as.factor(std$num_symptoms)
# std$num_symptoms = relevel(std$num_symptoms, ref="0")


factor.cols <-
  c(
    "race",
    # Race (W=white, B=black)
    "marital",
    # Marital status (D=divorced / separated, M=married, S=single)
    "iinfct",
    # Initial infection (1= gonorrhea, 2=chlamydia, 3=both)
    "os12m",
    # Oral sex within 12 months (1=yes, 0=no)
    "os30d",
    # Oral sex within 30 days (1=yes, 0=no)
    "rs12m",
    # Rectal sex within 12 months (1=yes, 0=no)
    "rs30d",
    # Rectal sex within 30 days (1=yes, 0=no)
    "abdpain",
    # Presence of abdominal pain (1=yes, 0=no)
    "discharge",
    # Sign of discharge (1=yes, 0=no)
    "dysuria",
    # Sign of dysuria (1=yes, 0=no)
    "condom",
    # Condom use (1=always, 2=sometime, 3=never)
    "itch",
    # Sign of itch (1=yes, 0=no)
    "lesion",
    # Sign of lesion (1=yes, 0=no)
    "rash",
    # Sign of rash (1=yes, 0=no)
    "lymph",
    # Sign of lymph (1=yes, 0=no)
    "vagina",
    # Involvement vagina at exam (1=yes, 0=no)
    "dchexam",
    # Discharge at exam (1=yes, 0=no)
    "abnode" # Abnormal node at exam (1=yes, 0=no)
  )
std[factor.cols] <- lapply(std[factor.cols], as.factor)
#lapply(std, class)
std$race <-
  mapvalues(std$race,
            from = c("W", "B"),
            to = c("White", "Black"))
std$marital <-
  mapvalues(
    std$marital,
    from = c("D", "M", "S"),
    to = c("Divorced/Separated", "Married", "Single")
  )
std$iinfct <-
  mapvalues(
    std$iinfct,
    from = c("1", "2", "3"),
    to = c("gonorrhea", "chlamydia", "both")
  )
std$condom <-
  mapvalues(
    std$condom,
    from = c("1", "2", "3"),
    to = c("always", "sometime", "never")
  )


surv_object <- Surv(time = std$time, event = std$rinfct)
```

```{r}
std0 = std0[which(std0$rinfct=="1"),]
std0$iinfct <-
  mapvalues(
    std0$iinfct,
    from = c("1", "2", "3"),
    to = c("gonorrhea", "chlamydia", "both")
  )
# Symptom Percentages based on Initial Infection

symptoms <- c("itch","lesion","rash","lymph", "abdpain","discharge","dysuria")
ii_sub1 <- std0[which(std0$iinfct=="gonorrhea"),symptoms]
ii_sub2 <- std0[which(std0$iinfct=="chlamydia"),symptoms]
ii_sub3 <- std0[which(std0$iinfct=="both"),symptoms] 

ii_sub1 <- colSums((ii_sub1))/nrow(ii_sub1)
ii_sub2 <- colSums((ii_sub2))/nrow(ii_sub2)
ii_sub3 <- colSums((ii_sub3))/nrow(ii_sub3)

ii_sub1["infection"] = "gonorrhea"
ii_sub2["infection"] = "chlamydia"
ii_sub3["infection"] = "both"

ii_symptom <- as.data.frame(rbind(ii_sub1, ii_sub2, ii_sub3))

ii_symptom_long <- pivot_longer(ii_symptom, !infection, names_to="Symptom",values_to="percentage")
ii_symptom_long$percentage <- as.numeric(ii_symptom_long$percentage)
```

```{r}
ggplot(ii_symptom_long,aes(x = infection,y = percentage, fill = Symptom)) + 
    geom_col(position="dodge") +
    scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
    labs(title="Percent of Symptoms of 3 Initial Infection Types",
         x="Initial Infection Type", y="Percentage")
```


```{r}
ggplot(std,aes(x = iinfct, fill = iinfct)) + 
    geom_bar(stat="count", position="dodge") +
    # scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
    labs(title="Number of Reinfection of 3 Initial Infection Types",
         x="Initial Infection Type", y="Count")
```
```{r}
ggplot(std[which(std$rinfct==1),],aes(x = iinfct, y = time , fill = iinfct)) + 
    geom_boxplot() +
    # scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
    labs(title="Reinfection Time of 3 Initial Infection Types",
         x="Initial Infection Type", y="Count")
```

```{r, fig.width=10, fig.height=8}
# number of symptoms
num_symptoms = rowSums(std0[,symptoms])
num_symptoms <-
  mapvalues(
    num_symptoms,
    from = c(0,1,2,3,4,5),
    to = c("0","1","2",">2",">2",">2")
  )

std0['num_symptoms'] = num_symptoms

par(mfrow=c(2,4))
boxplot(time ~ abdpain, data=std0)
boxplot(time ~ discharge, data=std0)
boxplot(time ~ dysuria, data=std0)
boxplot(time ~ itch, data=std0)
boxplot(time ~ lesion, data=std0)
boxplot(time ~ lymph, data=std0)
boxplot(time ~ rash, data=std0)
boxplot(time ~ num_symptoms, data=std0)
```


```{r}
KM_abdpain <- survfit(surv_object ~ abdpain, data = std)
KM_abdpain <- ggsurvplot(KM_abdpain) + labs(title = "Kaplan-Meier Curves for Abdominal Pain") 
KM_abdpain
```
```{r}
KM_os <- survfit(surv_object ~ os30d, data = std)
KM_os <- ggsurvplot(KM_os) + labs(title = "Kaplan-Meier Curves for Oral Sex Within Last 30 Days") 
# ggplotly(KM_os[[1]])
KM_os
```

